#!/usr/bin/env python
import sys
import logging
logging.basicConfig(level=logging.DEBUG)

from tornado.ioloop import IOLoop

from srcrcon import SrcRCON
from srcrcon.args import parser

if __name__ == '__main__':
    if len(sys.argv) < 2:
        parser.print_usage()
        sys.exit()
    args = parser.parse_args()
    app = SrcRCON(args.host, args.port, args.password or '')
    if args.command:
        app.send_single_command(args.command)
    #IOLoop.current().run_sync(app.send_single_command)
