#!/usr/bin/env python
import sys
import logging

from tornado.ioloop import IOLoop

from srcrcon import SrcRCON
from srcrcon.args import parser

if __name__ == '__main__':
    if len(sys.argv) < 2:
        parser.print_usage()
        sys.exit()

    args = parser.parse_args()

    if args.loglevel:
        logging.basicConfig(level=getattr(logging, args.loglevel.upper()))

    app = SrcRCON(args.host, args.port, args.password or '')

    if args.command:
        app.send_single_command(args.command)
        sys.exit()

    # interactive mode
    pass
